const { readFileSync, writeFileSync } = require('node:fs');
const { join } = require('node:path');
const fragments = ['firestore','profile','social','match-ownership','match-metadata','match-participation','venue'];
function assembleRules() {
  const body = fragments.map(name => `// ---- ${name} ----\n${readFileSync(join(__dirname, `${name}.fragment.rules`), 'utf8').trim()}`).join('\n\n');
  return `// GENERATED by node functions/rules/assemble.cjs. Local candidate; NOT deployed.\n// Edit fragments, regenerate, then test. Never append old broad allow blocks.\nrules_version = '2';\nservice cloud.firestore {\nmatch /databases/{database}/documents {\n${body}\n\nmatch /{document=**} { allow read, write: if false; }\n}\n}\n`;
}
function assembleStorageRules() {
  const body = ['storage','storage-profile'].map(name => readFileSync(join(__dirname,`${name}.fragment.rules`),'utf8').trim()).join('\n\n');
  return `// GENERATED by node functions/rules/assemble.cjs. Local candidate; NOT deployed.\nrules_version = '2';\nservice firebase.storage {\nmatch /b/{bucket}/o {\n${body}\n}\n}\n`;
}
if (require.main === module) {
  writeFileSync(join(__dirname,'firestore.candidate.rules'),assembleRules());
  writeFileSync(join(__dirname,'storage.candidate.rules'),assembleStorageRules());
}
module.exports = { assembleRules, assembleStorageRules };
