// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBbmrBTlxj-7CPaZnk0sHX-JEiTfIG6HM',
    appId: '1:2273283642:web:173370b982a7e2b3b72f03',
    messagingSenderId: '2273283642',
    projectId: 'halisaha-app-d9ea1',
    authDomain: 'halisaha-app-d9ea1.firebaseapp.com',
    storageBucket: 'halisaha-app-d9ea1.firebasestorage.app',
    measurementId: 'G-9K8KHGS6R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3foQkszRJEWjnUNahyvliOl3beaGlmg0',
    appId: '1:2273283642:android:f98b47c2b3ed52dbb72f03',
    messagingSenderId: '2273283642',
    projectId: 'halisaha-app-d9ea1',
    storageBucket: 'halisaha-app-d9ea1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxlWugk_WFHInhHH0vihrahPdYB3e76ow',
    appId: '1:2273283642:ios:4156208eddc08ea5b72f03',
    messagingSenderId: '2273283642',
    projectId: 'halisaha-app-d9ea1',
    storageBucket: 'halisaha-app-d9ea1.firebasestorage.app',
    iosBundleId: 'com.example.halisahaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxlWugk_WFHInhHH0vihrahPdYB3e76ow',
    appId: '1:2273283642:ios:4156208eddc08ea5b72f03',
    messagingSenderId: '2273283642',
    projectId: 'halisaha-app-d9ea1',
    storageBucket: 'halisaha-app-d9ea1.firebasestorage.app',
    iosBundleId: 'com.example.halisahaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBbmrBTlxj-7CPaZnk0sHX-JEiTfIG6HM',
    appId: '1:2273283642:web:5c165bc1e40d8876b72f03',
    messagingSenderId: '2273283642',
    projectId: 'halisaha-app-d9ea1',
    authDomain: 'halisaha-app-d9ea1.firebaseapp.com',
    storageBucket: 'halisaha-app-d9ea1.firebasestorage.app',
    measurementId: 'G-323HMZVN73',
  );
}
