name: Build iOS IPA

on:
  workflow_dispatch: 

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: 📥 Kodu çek
        uses: actions/checkout@v4

      - name: ⚙️ Flutter'ı kur
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 📦 Paketleri indir
        run: flutter pub get

      - name: 🧹 Temizlik, iOS 15.0 ve İmza Manipülasyonu
        # Podları siliyoruz, iOS 15.0'a sabitliyoruz ve Xcode'un imza zorunluluğunu hackliyoruz.
        run: |
          rm -f ios/Podfile
          rm -f ios/Podfile.lock
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]*\.[0-9]*/IPHONEOS_DEPLOYMENT_TARGET = 15.0/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGNING_REQUIRED = YES/CODE_SIGNING_REQUIRED = NO/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGNING_ALLOWED = YES/CODE_SIGNING_ALLOWED = NO/g' ios/Runner.xcodeproj/project.pbxproj

      - name: 🍏 Sertifikasız iOS Build Al
        # İşte sihir burada! Hata verse bile (Apple imza istese bile) işlemi durdurmayıp devam edecek.
        continue-on-error: true
        run: flutter build ios --release --no-codesign

      - name: 📦 Çıktıyı IPA Formatına Çevir
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r -9 app.ipa Payload/

      - name: 🚀 IPA Dosyasını İndirilebilir Yap
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: app.ipa
